### ISSUE TITLE
;)

### ISSUE THREAD

**Issue by vitaly-t** [lanetix/node-pg-connect#2]
Just in case you haven't come across, there is [pg-promise](https://github.com/vitaly-t/pg-promise) to do all the promise stuff for [node-postgres](https://github.com/brianc/node-postgres) ;)

Cheers!

**Comment by apechimp** [comment]
Ahh, yes, I have seen that: it's a very nice library. Thanks for making it :+1:. This package is intended to just implement the patterns mentioned in the [bluebird docs](https://github.com/petkaantonov/bluebird/blob/master/API.md#resource-management) for connection managment on top of node-postgres, and otherwise keep the exact node-postgres api. This was useful for me since I know that API very well, but am bad at returning connections to pools :wink:, so I figured I should publish it :smile:

**Comment by apechimp** [comment]
This is now deprecated since node-postgres 6 supports promises out of the box.
